#WEATHER OBSERVATION STATION-4
SELECT COUNT(CITY) - COUNT(DISTINCT CITY) AS difference
FROM STATION;

#WEATHER OBSERVATION STATION 6
select distinct city
from station
where city LIKE 'a%'
or city like 'e%'
or city like 'i%'
or city like 'o%'
or city like 'u%'

#WEATHER OBSERVATION STATION 7
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '[aeiou]$';

#WEATHER OBSERVATION STATION 8
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[aeiou].*[aeiou]$';

#WEATHER OBSERVATION STATION 9
SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT LIKE 'a%'
  AND CITY NOT LIKE 'e%'
  AND CITY NOT LIKE 'i%'
  AND CITY NOT LIKE 'o%'
  AND CITY NOT LIKE 'u%';

#WEATHER OBSERVATION STATION 10
SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT LIKE '%a'
  AND CITY NOT LIKE '%e'
  AND CITY NOT LIKE '%i'
  AND CITY NOT LIKE '%o'
  AND CITY NOT LIKE '%u';



