#WEATHER OBSRVATION STATION 11
SELECT DISTINCT CITY 
FROM STATION
WHERE CITY NOT REGEXP '^[AEIOUaeiou]'
   OR CITY NOT REGEXP '[AEIOUaeiou]$';

#WEATHER OBSERVATION STATION 12
SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT REGEXP '^[AEIOUaeiou]'
  AND CITY NOT REGEXP '[AEIOUaeiou]$';

#HIGHER THAN 75
SELECT NAME 
FROM STUDENTS 
WHERE MARKS>75
ORDER BY RIGHT (NAME,3), ID ASC;

#EMPLOYEE NAMES
SELECT NAME
FROM EMPLOYEE
ORDER BY NAME ASC;

#EMPLOYEE SALARIES
SELECT name
FROM Employee
WHERE salary > 2000
AND months < 10
ORDER BY employee_id ASC; 